/**
 * Brand Constitution - The AI-generated "DNA" of a brand
 * Generated by Agent A (The Archivist) from moodboard analysis
 */
export interface BrandConstitution {
    visual_identity: {
        color_palette_hex: string[];
        photography_style: string;
        forbidden_elements: string[];
    };
    voice: {
        tone: string;
        keywords: string[];
    };
    risk_thresholds: {
        nudity: "STRICT_ZERO_TOLERANCE" | "ALLOW_ARTISTIC";
        political: "STRICT_ZERO_TOLERANCE" | "ALLOW_SATIRE";
    };
}

/**
 * Canvas element types for the moodboard
 */
export type CanvasElementType = "image" | "note" | "color";

/**
 * Individual element on the brand canvas
 */
export interface CanvasElement {
    id: string;
    type: CanvasElementType;
    hash?: string; // SHA-256 hash for deduplication
    name?: string;
    // Position on canvas
    x: number;
    y: number;
    // Type-specific data
    url?: string; // For images
    text?: string; // For notes
    color?: string; // For color swatches (hex)
    // Metadata
    createdAt: number;
}

/**
 * Processed asset cache entry - used for deduplication
 */
export interface ProcessedAsset {
    type: CanvasElementType;
    extracted_rules: Partial<BrandConstitution>;
    timestamp: number;
}

/**
 * Brand document in Firestore
 */
export interface Brand {
    id: string;
    name: string;
    canvas_elements: CanvasElement[];
    constitution_cache: BrandConstitution | null;
    processed_assets: Record<string, ProcessedAsset>;
    last_updated: number;
    created_at: number;
}

/**
 * Create a new empty brand
 */
export function createEmptyBrand(id: string, name: string): Brand {
    return {
        id,
        name,
        canvas_elements: [],
        constitution_cache: null,
        processed_assets: {},
        last_updated: Date.now(),
        created_at: Date.now(),
    };
}

/**
 * Create a new canvas element
 */
export function createCanvasElement(
    type: CanvasElementType,
    data: Partial<CanvasElement>
): CanvasElement {
    return {
        id: crypto.randomUUID(),
        type,
        x: data.x ?? 0,
        y: data.y ?? 0,
        url: data.url,
        text: data.text,
        color: data.color,
        hash: data.hash,
        name: data.name,
        createdAt: Date.now(),
    };
}
